### ISSUE TITLE
Incompatible with iperf3, but missing explanation (MTWJ-431) 

### ISSUE THREAD

**Issue by leeebo** [espressif/iperf-cmd#1]
The readme points to a link https://iperf.fr/iperf-doc.php, which is the official site of iperf3, download the binary from the website will not work for users.

**PC as a server, ESP as a client**. Users will experience the following errors:

TCP Test:

`iperf3: error - unable to receive parameters from client:`

UDP Test:

`no output`

from Wireshark : [UDP packet loss or out of order delivery]

**Comment by leeebo** [comment]
iperf2: https://sourceforge.net/projects/iperf2/

**Comment by ydhub** [comment]
I'll check and update.

**Comment by ydhub** [comment]
Hi @leeebo 

> Part of official iperf: https://iperf.fr/iperf-doc.php

The link https://iperf.fr/iperf-doc.php includes iperf2 (https://iperf.fr/iperf-doc.php#doc) and iperf3 commands. The component only support part of iperf (2.0).

Anyway, the README should be updated to reduce misunderstandings.
